export const SET_REVIEWER_DETAILS = 'rateMovie/SET_REVIEWER_DETAILS';
export const SET_REVIEWER_QUESTIONS = 'rateMovie/SET_REVIEWER_QUESTIONS';
export const SET_REVIEWER_RATINGS = 'rateMovie/SET_REVIEWER_RATINGS';
export const SET_CURRENT_STEP = 'rateMovie/SET_CURRENT_STEP';
